DROP DATABASE if EXISTS 3bb;
CREATE DATABASE 3bb;

USE 3bb;

CREATE TABLE 3bb_usuario (
	id INT NOT NULL AUTO_INCREMENT, 
	nome VARCHAR(32) NULL DEFAULT NULL, 
	senha VARCHAR(32) NULL DEFAULT NULL, 
	tel VARCHAR(32) NULL DEFAULT NULL, 
	image VARCHAR(150) NULL DEFAULT NULL, 
	PRIMARY KEY (id)
);